# Generated by Django 5.1.2 on 2024-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPel', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID Pelanggan')),
                ('namaDpn', models.CharField(max_length=50, verbose_name='Nama Depan')),
                ('namaBlkng', models.CharField(max_length=50, verbose_name='Nama Belakang')),
                ('jkPel', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('alamatPel', models.TextField(max_length=300, verbose_name='Alamat')),
                ('pekerjaan', models.CharField(max_length=50, verbose_name='Pekerjaan')),
                ('tglLahirPel', models.DateField(verbose_name='Tanggal Lahir')),
            ],
            options={
                'verbose_name_plural': 'Data Pelanggan',
                'ordering': ['idPel'],
            },
        ),
    ]
