# Generated by Django 5.1.2 on 2024-12-18 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoTlpPel',
            fields=[
                ('idNoTlpPel', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Nomor Telepon')),
                ('noTlpPel', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Nomor telepon hanya boleh berisi angka.')], verbose_name='Nomor Telepon')),
                ('idPel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomor_telepon', to='order.pelanggan', verbose_name='ID Pelanggan')),
            ],
        ),
    ]
