# Generated by Django 5.1.2 on 2024-12-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_pesan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPesan',
            fields=[
                ('idDetailPesan', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detail Pemesanan')),
                ('tglCheckIn', models.DateField(verbose_name='Tanggal Check In')),
                ('tglCheckOut', models.DateField(verbose_name='Tanggal Check Out')),
                ('statusPesan', models.CharField(choices=[('A', 'APPROVED'), ('C', 'CANCELLED'), ('D', 'DONE')], default='A', max_length=1, verbose_name='Status Pesan')),
                ('idKamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.kamar', verbose_name='ID Kamar')),
                ('idPesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.pesan', verbose_name='ID Pemesanan')),
            ],
            options={
                'verbose_name_plural': 'Data Detail Pesan',
                'ordering': ['idDetailPesan'],
            },
        ),
    ]
