# Generated by Django 5.1.2 on 2024-12-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_detailpesan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='namaBlkng',
            field=models.CharField(max_length=100, verbose_name='Nama Belakang'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='namaDpn',
            field=models.CharField(max_length=100, verbose_name='Nama Depan'),
        ),
    ]
